export interface Deal {
  id: string;
  restaurantName: string;
  title: string;
  subtitle: string;
  promoText: string;
  ctaText: string;
  image: any;
  timeRange: string;
}

export const mockDeals: Deal[] = [
  {
    id: "1",
    restaurantName: "Wooden City Spokane",
    title: "Chef's Table – Happy Hour!",
    subtitle: "20% off all cocktails from 5 PM to 7 PM",
    promoText: "20%",
    ctaText: "Get Your Drink Now!",
    image: require("@/assets/media/pp-1.png"),
    timeRange: "5 PM to 7 PM",
  },
  {
    id: "2",
    restaurantName: "Clinkerdagger",
    title: "Bella Cucina – Pizza Lovers' Special!",
    subtitle: "Buy one, get one free on all pizzas from 12 PM to 3 PM",
    promoText: "BOGO",
    ctaText: "Claim Your Pizza!",
    image: require("@/assets/media/pp-2.png"),
    timeRange: "12 PM to 3 PM",
  },
  {
    id: "3",
    restaurantName: "Paella Bar",
    title: "Golden Olive – Tapas Time!",
    subtitle: "Enjoy 3 tapas for the price of 2 between 4 PM and 6 PM",
    promoText: "3 for 2",
    ctaText: "Grab This Deal!",
    image: require("@/assets/media/cafe.jpg"),
    timeRange: "4 PM to 6 PM",
  },
  {
    id: "4",
    restaurantName: "Wooden City Spokane",
    title: "Burger Bonanza!",
    subtitle: "Get 30% off burgers from 6 PM to 9 PM",
    promoText: "30%",
    ctaText: "Get Your Burger!",
    image: require("@/assets/media/pp-1.png"),
    timeRange: "6 PM to 9 PM",
  },
  {
    id: "5",
    restaurantName: "Sushi Haven",
    title: "Sushi Roll Extravaganza!",
    subtitle: "All-you-can-eat sushi rolls for $25 from 11 AM to 2 PM",
    promoText: "$25",
    ctaText: "Reserve Your Spot!",
    image: require("@/assets/media/pp-2.png"),
    timeRange: "11 AM to 2 PM",
  },
  {
    id: "6",
    restaurantName: "Steakhouse Prime",
    title: "Prime Cut Special!",
    subtitle: "50% off all steaks every Tuesday from 5 PM to 10 PM",
    promoText: "50%",
    ctaText: "Book Now!",
    image: require("@/assets/media/cafe.jpg"),
    timeRange: "5 PM to 10 PM",
  },
  {
    id: "7",
    restaurantName: "Taco Fiesta",
    title: "Taco Tuesday Madness!",
    subtitle: "$1 tacos all day long on Tuesdays",
    promoText: "$1",
    ctaText: "Get Your Tacos!",
    image: require("@/assets/media/pp-1.png"),
    timeRange: "All Day",
  },
  {
    id: "8",
    restaurantName: "The French Corner",
    title: "Brunch & Bubbles!",
    subtitle: "Free mimosas with any brunch entrée on weekends",
    promoText: "FREE",
    ctaText: "Claim Your Brunch!",
    image: require("@/assets/media/pp-2.png"),
    timeRange: "10 AM to 3 PM",
  },
  {
    id: "9",
    restaurantName: "Dragon Wok",
    title: "Dim Sum Delight!",
    subtitle: "20% off all dim sum dishes from 1 PM to 4 PM",
    promoText: "20%",
    ctaText: "Order Now!",
    image: require("@/assets/media/cafe.jpg"),
    timeRange: "1 PM to 4 PM",
  },
  {
    id: "10",
    restaurantName: "Seafood Shack",
    title: "Oyster Hour Special!",
    subtitle: "$1 oysters from 4 PM to 6 PM daily",
    promoText: "$1",
    ctaText: "Shuck 'Em Now!",
    image: require("@/assets/media/pp-1.png"),
    timeRange: "4 PM to 6 PM",
  },
  {
    id: "11",
    restaurantName: "Pasta Paradise",
    title: "Italian Night!",
    subtitle: "Buy any pasta, get a free dessert from 6 PM to 9 PM",
    promoText: "FREE",
    ctaText: "Grab This Offer!",
    image: require("@/assets/media/pp-2.png"),
    timeRange: "6 PM to 9 PM",
  },
  {
    id: "12",
    restaurantName: "BBQ Pit Stop",
    title: "Smokin' Hot Deal!",
    subtitle: "Family platter for 4 only $49.99 on weekends",
    promoText: "$49.99",
    ctaText: "Feed the Family!",
    image: require("@/assets/media/cafe.jpg"),
    timeRange: "All Day",
  },
  {
    id: "13",
    restaurantName: "Veggie Delight",
    title: "Plant-Based Power!",
    subtitle: "25% off all vegan dishes from 12 PM to 8 PM",
    promoText: "25%",
    ctaText: "Go Green Today!",
    image: require("@/assets/media/pp-1.png"),
    timeRange: "12 PM to 8 PM",
  },
  {
    id: "14",
    restaurantName: "Clinkerdagger",
    title: "Wine & Dine Wednesday!",
    subtitle: "Half-price bottles of wine with any dinner entrée",
    promoText: "50%",
    ctaText: "Sip & Save!",
    image: require("@/assets/media/pp-2.png"),
    timeRange: "5 PM to 11 PM",
  },
];
